# Asignación 1

Todos los asignaciones serán presentadas utilizando los cuadernos de [Jupyter Notebook](http://jupyter.org/), además de respectivas pruebas como ejemplo, así como el uso de mediciones de velocidad de ejecución utilizando  el comando `timeit` y algunos gráficos si fuese necesario.

##  Lista de ejercicios

1 . Escriba un programa que genere *"Hola, mundo!"*  (si las comillas) en la línea de comandos de Python.

In [1]:
# Tu codigo



2 . [El archivo1](https://github.com/CC-001/Asignacion1/blob/master/archivo1.py), presenta código fuente Python acerca de diversos aspectos útiles para análisis de datos. Presenta un reporte de cada una de las lineas presentadas, con ejemplos de las funciones que componen cada módulo. Tu reporte debe presentar, explicación acerca de los siguientes ítems:

* Funciones de cadena básicas.
* Estructura de datos de python: Lista y diccionarios, conjuntos. Tu reporte de tener información de cosas, como que `sets` puede almacenar por ejemplo una copia de un ítem y tiene un tiempo de búsqueda sublineal de `O(log(N))`.
* Lista de comprensión.
* Modulo `collections` y el constructor `Counter`.
* Módulo `pickle`.
* Búsqueda en la web con `ùrllib` para python 3.

In [2]:
# Tu reporte y código

3 . El siguiente ejercicio ([archivo2](https://github.com/CC-001/Asignacion1/blob/master/archivo2.py)) es acerca de expresiones regulares. Explica y implementa los métodos de los módulos `re` y `glob`, descritos en el archivo, así como ejemplos de expresiones regulares. Presenta un archivo con código python, así como un reporte de:

* Módulo `re` y `glob`.

In [3]:
# Tu respuesta

4 . A lo largo del curso aprenderemos cómo extraer datos de archivos de discos locales e internet y almacenarlos en estructuras de datos apropiadas, extraer código que coincidan con ciertos patrones y almacenarlo  para procesamientos futuros. No hay nada infinito en Ciencia de la computación, pero hay un número infinito de escenarios que requieren extracción de datos, variando en tipo, propósito y complejidad. Éstos son sólo algunos de ellos:

#### Contador de frecuencia de palabras 

Escribe un programa que descargue una página web solicitada por el usuario y reporte  hasta las diez palabras más usadas. El programa debe tratar todas las palabras como mayúsculas y minúsculas sin ninguna diferencia. Para el propósito de este ejercicio, suponga que una palabra es descrita por la expresión regular `r"\w+"`.

In [4]:
# Tu codigo

#### Indexador de archivos 

Escriba un programa que indexe todos los archivos en un determinado directorio (carpeta) designado por el usuario. El programa debe construir un diccionario en el que las claves sean palabras únicas en todos los archivos y el valor de cada entrada es una lista de nombre de  archivos  que contienen la palabra. Por ejemplo, si la palabra `aloha` se menciona en los archivos `early-internet.dat` y `hawaiian-travel.txt`, el diccionario tendrá una entrada `{..., 'aloha': ['early-internet .dat ',' hawaiian-travel.txt '], ...}`.


El programa almacenará  el diccionario para un uso futuro.

In [5]:
# Tu codigo

#### Extractor de números teléfonicos

Escribe un programa que extrae todos los números teléfonicos de un archivo de texto dado. Esto no es una tarea fácil, ya que hay varias docenas de convenciones nacionales para escribir números teléfonicos (ver [https://en.wikipedia.org/wiki/National_conventions_for_writing_telephone_numbers](en.wikipedia.org/ / National_conventions_for_writing_telephone_numbers)). ¿Puedes diseñar una expresión regular que contenga  a todos los números telefónicos?.

In [6]:
# Tu código

3 . Numpy es un excelente conjunto de herramientas cuando se trata de números. Numpy muy amable, trata a los vectores y  matrices como ciudadanos de primera clase; les proporciona operaciones aritméticas, lógicas y operaciones vectorizadas; y  proporciona un medio para la remodelación de datos, ordenación y agregación, incluso suministra una criatura  llamada `nan`, que es un número que no es un número.

#### Diferenciador de matrices(array)

Las sumas parciales son un equivalente aproximado de una integral. En efecto, el cálculo define una integral como una suma infinita de elementos infinitesimales. Las *diferencias de matrices parciales*  $arr_{i + 1}-arr_i$ son un equivalente aproximado de la derivada. Numpy no proporciona una herramienta para calcular las diferencias de matrices parciales. Escriba un programa que, dado una matriz `arr`, calcula las diferencias parciales de los elementos de la matriz (array). Asume que la matriz es numérica.

Sugerencia: Escoge algun tipo de conjunto de datos y escribe que `diff = array[1:] - array[:-1]`. 

In [7]:
# Tu codigo



4 . En este ejercicio se pide algunas implementaciones de Numpy:

In [8]:
import numpy as np

print ("Hace una matriz  3x 4 de numeros aleatorios")
x = np.random.rand(3, 4)
print (x)

print ("Agrega  1 a cada elemento")
x = x + 1
print (x)

print ("Conseguimos el elemento de la fila 1  column 2")
print (x[1, 2])
 
print ("Obtenemos la primera fila")
print (x[0, :])
print

print ("Segunda columna de la primera fila")
print (x[0, ::2])

Hace una matriz  3x 4 de numeros aleatorios
[[ 0.79641412  0.42560887  0.95286585  0.57429055]
 [ 0.95472136  0.78135265  0.59359939  0.24449156]
 [ 0.17175467  0.25954079  0.45124478  0.24202577]]
Agrega  1 a cada elemento
[[ 1.79641412  1.42560887  1.95286585  1.57429055]
 [ 1.95472136  1.78135265  1.59359939  1.24449156]
 [ 1.17175467  1.25954079  1.45124478  1.24202577]]
Conseguimos el elemento de la fila 1  column 2
1.59359938712
Obtenemos la primera fila
[ 1.79641412  1.42560887  1.95286585  1.57429055]
Segunda columna de la primera fila
[ 1.79641412  1.95286585]


Imprime el máximo, el mínimo y la media de la matriz. Además escribe `x.m <TAB>`, para encontrar las operaciones integradas comunes de estadística para la matriz. Presenta ejemplos: 

In [9]:
# Tu codigo

Llama a la función `x.max`  pero utilice la palabra clave `axis` para imprimir el máximo de cada fila en `x`.

In [10]:
# Tu codigo

He aquí una manera de simular rápidamente `500` lanzamientos de monedas (donde la probabilidad de obtener caras es del `50%` o  `0,5`).

In [11]:
x = np.random.binomial(500, .5)
print ("numero de caras :", x)

numero de caras : 254


Repita esta simulación `500` veces y use la función `plt.hist()` para trazar un histograma del número de caras en cada simulación.

In [12]:
# La respuesta es...

5 . Explica el  siguiente código, línea por línea:

In [13]:
seq = ['Python', 'R']
iterador = iter(seq)
while True:
    try:
        x = iterador.__next__()
        print(x)
    except StopIteration as e:
        break


Python
R


6 . El pseudocódigo de iteración se implementa realmente en cPython generando código de byte cuando se encuentra un bucle `for`. Aquí hay un ejemplo de bytecode de iteración real, usando el módulo `dis` de la biblioteca estándar de Python. El módulo `dis` desmonta el código en código de byte. Explica las siguiente lineas:

In [14]:
def bucle(seq):
    for x in seq:
        print (x)

In [15]:
import dis
dis.dis(bucle)

  2           0 SETUP_LOOP              24 (to 27)
              3 LOAD_FAST                0 (seq)
              6 GET_ITER
        >>    7 FOR_ITER                16 (to 26)
             10 STORE_FAST               1 (x)

  3          13 LOAD_GLOBAL              0 (print)
             16 LOAD_FAST                1 (x)
             19 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
             22 POP_TOP
             23 JUMP_ABSOLUTE            7
        >>   26 POP_BLOCK
        >>   27 LOAD_CONST               0 (None)
             30 RETURN_VALUE


7 . En que consiste el protocolo interador (The Iterator Protocol) de Python.

In [16]:
# Tu respuesta